# finance-app-backend/schemas/orchestration_data.py

from pydantic import BaseModel, Field, condecimal
from decimal import Decimal
from typing import List, Dict, Any

# Define precision for all financial fields (up to 12 digits total, 2 decimal places)
FinancialDecimal = condecimal(max_digits=12, decimal_places=2)

# Import the standardized leakage item structure
# NOTE: Ensure this path is correct based on your file structure
from .leakage_data import LeakageBucket 


# ----------------------------------------------------------------------
# V2 Behavioral ML & Real-Time Recalculation (Insight & Leak View)
# ----------------------------------------------------------------------

class ProactiveInsight(BaseModel):
    """Schema for a single proactive 'Insight Card' generated by the InsightService."""
    type: str = Field(..., description="The insight type (e.g., 'CRITICAL_LEAK_WARNING').")
    title: str = Field(..., description="The headline text for the insight card.")
    body: str = Field(..., description="The detailed, actionable message.")
    action: str = Field(..., description="The required user action hook (e.g., 'VIEW_LEAK_IMPACT').")
    priority: int = Field(..., description="Priority level for display (0 is highest).")


class RecalculationResponse(BaseModel):
    """
    Schema for the response after a transaction triggers the Autopilot Orchestration.
    Includes the new reclaimable fund and the proactive insights/leak breakdown.
    """
    projected_reclaimable: FinancialDecimal = Field(Decimal("0.00"), description="The new total reclaimable salary MTD (Overall Leak).")
    insights: List[ProactiveInsight] = Field(..., description="List of current proactive and reactive insight cards for the user.")
    # 🌟 FIXED: Using the imported, standardized LeakageBucket item
    category_leaks: List[LeakageBucket] = Field(..., description="Category-wise leak breakdown for the Leak Bucket View.")


# ----------------------------------------------------------------------
# V2 Guided Orchestration: Suggestion & Consent
# ----------------------------------------------------------------------

class TransferSuggestion(BaseModel):
    """A single rule-based suggestion from the Autopilot, derived from the SmartTransferRule."""
    rule_id: int
    rule_name: str
    transfer_amount: FinancialDecimal
    destination: str
    type: str = Field(..., description="Rule category: 'TAX_SAVING', 'GOAL_STASH', 'DUES_PAYMENT'.")

class SuggestionPlanResponse(BaseModel):
    """Response from generate_consent_suggestion_plan."""
    available_fund: FinancialDecimal
    remaining_unallocated: FinancialDecimal
    total_suggested: FinancialDecimal
    suggestion_plan: List[TransferSuggestion]
    message: str

class ExecutionResponse(BaseModel):
    """Response from record_consent_and_update_balance (Autopilot execution)."""
    status: str
    message: str
    total_transferred: FinancialDecimal
    transfers_executed: List[TransferSuggestion]
